// Continuum bootstrap. Runs on every `npm run dev` and `npm run build`. Idempotent.
//
// What it does (only when needed):
//   1. Generates .env with random ENCRYPTION_KEY + CONTINUUM_TOKEN (if missing).
//   2. Validates DATABASE_URL is a postgres:// URL.
//   3. Runs `prisma db push` to create/upgrade the schema.
//   4. Seeds the admin password (default: "continuum") if none is set yet.
//
// First-run leaves the database otherwise empty — users register their own
// real projects either by opening Claude Code in a git repo (auto-register
// hook) or via the /projects UI.

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { execSync } from "node:child_process";
import { resolve } from "node:path";

const ROOT = resolve(__dirname, "..");
const ENV_PATH = resolve(ROOT, ".env");
const DOCKER_LOCAL_DB_URL =
  "postgresql://continuum:continuum@localhost:5432/continuum";

function log(msg: string) {
  process.stdout.write(`\x1b[36m[continuum]\x1b[0m ${msg}\n`);
}

function die(msg: string): never {
  process.stderr.write(`\x1b[31m[continuum]\x1b[0m ${msg}\n`);
  process.exit(1);
}

function readEnv(): Record<string, string> {
  if (!existsSync(ENV_PATH)) return {};
  const lines = readFileSync(ENV_PATH, "utf8").split("\n");
  const out: Record<string, string> = {};
  for (const line of lines) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
    if (!m) continue;
    let val = m[2].trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    out[m[1]] = val;
  }
  return out;
}

function ensureEnvFile() {
  // Read whatever exists; treat empty string as "missing" so we backfill.
  const current = existsSync(ENV_PATH) ? readEnv() : {};

  const needs = {
    // Never silently bake in a default — the user might not have a local
    // Postgres running. Leave it empty so validateDatabaseUrl can ask them
    // to fill it in.
    DATABASE_URL: current.DATABASE_URL ?? "",
    ENCRYPTION_KEY:
      current.ENCRYPTION_KEY || randomBytes(32).toString("hex"),
    CONTINUUM_TOKEN: current.CONTINUUM_TOKEN || randomBytes(24).toString("hex"),
    ANTHROPIC_API_KEY: current.ANTHROPIC_API_KEY ?? "",
    OPENAI_API_KEY: current.OPENAI_API_KEY ?? "",
    DEMO_MODE: current.DEMO_MODE ?? "",
  };

  const changed: string[] = [];
  for (const [k, v] of Object.entries(needs)) {
    if (current[k] !== v && v) changed.push(k);
  }

  if (!existsSync(ENV_PATH)) {
    log("creating .env (first run)");
  } else if (changed.length > 0) {
    log(`backfilling ${changed.join(", ")}`);
  }

  if (!existsSync(ENV_PATH) || changed.length > 0) {
    const lines = [
      "# Generated by Continuum bootstrap. Safe to edit.",
      `DATABASE_URL="${needs.DATABASE_URL}"`,
      `ENCRYPTION_KEY="${needs.ENCRYPTION_KEY}"`,
      `CONTINUUM_TOKEN="${needs.CONTINUUM_TOKEN}"`,
      `ANTHROPIC_API_KEY="${needs.ANTHROPIC_API_KEY}"`,
      `OPENAI_API_KEY="${needs.OPENAI_API_KEY}"`,
      `DEMO_MODE="${needs.DEMO_MODE}"`,
      "",
    ];
    writeFileSync(ENV_PATH, lines.join("\n"), "utf8");
  }

  const refreshed = readEnv();
  for (const [k, v] of Object.entries(refreshed)) {
    if (v && !process.env[k]) process.env[k] = v;
  }
}

function validateDatabaseUrl() {
  const url = process.env.DATABASE_URL ?? "";
  if (!url) {
    die(
      `DATABASE_URL is not set.\n` +
        `\n` +
        `Edit .env and add your Postgres connection string, e.g.:\n` +
        `  DATABASE_URL=postgresql://user:password@host:5432/dbname\n` +
        `\n` +
        `If you want a local Postgres without installing one, run:\n` +
        `  docker compose up -d\n` +
        `then use:\n` +
        `  DATABASE_URL=${DOCKER_LOCAL_DB_URL}`,
    );
  }
  if (!/^postgres(ql)?:\/\//.test(url)) {
    die(
      `DATABASE_URL must be a postgres:// or postgresql:// URL. Got: ${url}`,
    );
  }
}

function ensureSchema() {
  log("pushing prisma schema…");
  try {
    execSync("npx prisma db push --skip-generate --accept-data-loss", {
      cwd: ROOT,
      stdio: "inherit",
      env: process.env,
    });
  } catch {
    die(
      "prisma db push failed — is the database reachable?\n" +
        "  • Local: run `docker compose up -d` and try again.\n" +
        "  • Hosted: double-check the DATABASE_URL in .env.",
    );
  }
}

async function seedSelfHostWorkspace() {
  // Self-host = "one workspace, one user". Cloud mode never calls this
  // (Clerk webhook provisions workspaces per signup instead). The lazy
  // imports below are because the prisma client is regenerated by the
  // db push that runs above us — at module-load time it might not exist
  // yet for a fresh clone.
  if (
    process.env.CONTINUUM_MULTI_TENANT === "1" ||
    process.env.CONTINUUM_MULTI_TENANT === "true"
  ) {
    log("cloud mode — skipping self-host workspace seed");
    return;
  }

  const { prisma } = await import("../src/lib/db");
  const { SELF_HOST_WORKSPACE_SLUG } = await import("../src/lib/tenant");

  // Workspace
  const ws = await prisma.workspace.upsert({
    where: { slug: SELF_HOST_WORKSPACE_SLUG },
    update: {},
    create: {
      slug: SELF_HOST_WORKSPACE_SLUG,
      name: "Personal",
      tier: "self_hosted",
    },
  });

  // Local self-host user. Mirrors what Clerk would create in cloud mode.
  const user = await prisma.user.upsert({
    where: { externalId: "self-hosted" },
    update: {},
    create: {
      externalId: "self-hosted",
      name: "Self-hosted",
    },
  });

  // Membership
  await prisma.workspaceMember.upsert({
    where: { workspaceId_userId: { workspaceId: ws.id, userId: user.id } },
    update: {},
    create: { workspaceId: ws.id, userId: user.id, role: "owner" },
  });

  // Settings row (one per workspace)
  await prisma.settings.upsert({
    where: { workspaceId: ws.id },
    update: {},
    create: { workspaceId: ws.id },
  });

  // Seed the default admin password if one isn't set yet.
  const { seedDefaultPasswordIfMissing, DEFAULT_ADMIN_PASSWORD } = await import(
    "../src/lib/auth"
  );
  const seeded = await seedDefaultPasswordIfMissing(ws.id);
  if (seeded) {
    log(
      `seeded admin password: "${DEFAULT_ADMIN_PASSWORD}" — change it in /settings after first login`,
    );
  }
}

async function main() {
  // Docker builds run `next build` without a reachable DB. The image's
  // runtime entrypoint runs the real bootstrap when the container actually
  // starts. CONTINUUM_BUILD_ONLY=1 lets us skip everything DB-touching at
  // build time without ripping bootstrap out of the build script.
  if (
    process.env.CONTINUUM_BUILD_ONLY === "1" ||
    process.env.CONTINUUM_SKIP_BOOTSTRAP === "1"
  ) {
    log("CONTINUUM_BUILD_ONLY/SKIP_BOOTSTRAP set — skipping env/schema/seed");
    return;
  }
  ensureEnvFile();
  validateDatabaseUrl();
  ensureSchema();
  try {
    await seedSelfHostWorkspace();
  } catch (e) {
    log(`warning: could not seed self-host workspace (${(e as Error).message})`);
  }
  log("ready");
}

main().catch((e) => {
  console.error("[continuum] bootstrap failed:", e);
  process.exit(1);
});
